name: Build Android APK

on:
  push:
    branches:
      - hl_urbicide
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools-version: '33.0.0'
          target-sdk-level: 33

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Release APK
        working-directory: android
        run: ./gradlew clean assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Urbicide-APK
          path: android/app/build/outputs/apk/release/app-release.apk
